name: Publish Release Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      # Uses the branch for tag and master for releases https://github.com/marketplace/actions/publish-docker
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: marcellodesales/gitman
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

